### ISSUE TITLE
Error in npm run build

### ISSUE THREAD

**Issue by surferwat** [interledgerjs/minute#7]
I followed Quick Start instructions in README.md, but got an error in npm run build.

**Snippet of error log**

> find node_modules -name '*.pem' -exec rm \{\} \; ; ./node_modules/.bin/webpack

File not found - '*.pem'

**Comment by retryW** [comment]
I also get this error.  Output from npm log file below:

```
10 silly lifecycle   'find node_modules -name \'*.pem\' -exec rm \\{\\} \\; ; ./node_modules/.bin/webpack' ]
11 silly lifecycle minute@1.1.1~build: Returned: code: 2  signal: null
12 info lifecycle minute@1.1.1~build: Failed to exec build script
13 verbose stack Error: minute@1.1.1 build: `find node_modules -name '*.pem' -exec rm \{\} \; ; ./node_modules/.bin/webpack`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (D:\nodejs\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (D:\nodejs\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
D:\Users\Administrator\minute>
```

**Comment by adornala** [comment]
You might be building resources in windows. Do one thing!

Install Cygwin from [here](https://www.cygwin.com/)
Make sure you have node installed globally then open cygwin terminal(C:\cygwin64 (default))
from there navigate to root of your project and run `npm install` and `npm run build`

> Hack: if `npm run build` doesn't work -> get build script from package.json and run it in your terminal, split commands if required.

I think that script will fail for sure if executed in windows.
